### ISSUE TITLE
Set URIs via an input parameter that is a query

### ISSUE THREAD

**Issue by rjrudin** [marklogic/corb2#10]
getUriLoader() in Manager.java requires that the impl of UrisLoader either be QueryUrisLoader, FileUrisLoader, or a custom implementation of UrisLoader. That means the query must either in the modules database, on the filesystem, or in a custom implementation of UrisLoader. This makes it very difficult to programmatically define custom queries, as they must be in one of those 3 places.

Instead, I'd like to be able to set an input param such as URIS-QUERY="cts:uris(...)". getUrisLoader() could then check for that input, and if it exists, create an instance of QueryUrisLoader with the value of URIS-QUERY as the query to be executed. 

QueryUrisLoader can then be modified to get adhocQuery (currently line 110) from an instance variable as opposed to reading it from the filesystem or a modules database. 

This then opens the door for being able to invoke corb without any dependencies on modules on the filesystem or in the modules database - they can instead be passed in as strings (I'll have another ticket for doing this for the process module as well). What I have in mind is in something like Groovy shell, a developer ought to be able to do something like this:

    ml.corb().transformCollection("collection-name", "xdmp:node-insert-child(doc($URI)/element(), <test/>")

That transform collection would construct a uris query on the given collection, and then the 2nd arg would be the process module code. More complicated corb jobs would still most likely use files in the modules database, but for quick/simple corb jobs, this would be very flexible and easy.

I'm happy to put together a PR for this if this seems useful to others.

**Comment by rjrudin** [comment]
Another example for shell usage:

    ml.corb().deleteCollection("collection-name")

That would construct a uris query for the given collection, and then a simple process module of "xdmp:document-delete($URI)". That would be very handy for deleting collections that are too large to delete in qconsole, but it's annoying to have to create two modules just to get this done.

**Comment by bbandlamudi** [comment]
Hi Rob, 
I am little unclear about URIS-QUERY option. Since we can do URIS-MODULE=my-module.xqy|ADHOC where my-module.xqy stays in local file system (wherever corb is running from, not modules db), I am wondering if this would suffice instead of URIS-QUERY input param.

**Comment by rjrudin** [comment]
URIS-MODULE requires that the module exist on the filesystem. URIS-QUERY would allow for the module to be created programmatically and passed in as a string without ever being written to the filesystem. This is useful in allowing corb to be invoked from another program vs having to be invoked from the command line. Ideally, that program could eventually do something like this:

    Manager m = new Manager()
    m.setConnectionString(...)
    m.setUrisQuery("cts:uris(...)")
    m.setProcessTask("some.class.name")
    m.setThreadCount(4)
    m.run()

corb has always been a command-line driven tool, and I think it would increase its usability by developing the above sort of API underneath the command-line interface.

**Comment by bbandlamudi** [comment]
I started adding a new option URIS-QUERY, which is fairly easy. But I couldn't figure out an intuitive way to specify the language i.e., javascript or xquery. If none specified, xcc defaults to xquery. We can come up with two options URIS-QUERY and URIS-QUERY-JAVASCIPT, but I prefer a single option and optionally pass in language as part of the query string definition. Any ideas?

**Comment by mpheckel** [comment]
Rob, in case you aren’t familiar with it.. the ModuleExecutor class can be used for single stage transforms like deleting docs within a collection.  It was written to replace an old app called runXQuery.  It can handle queries written in either XQuery or JavaScript.  It’s discussed at the bottom of the readMe.md file.

**Comment by rjrudin** [comment]
I don't think ModuleExecutor will address my use case, because it too requires a module either in the database or on the filesystem. 

What I'm after is a way to run corb without having to reference a module on the filesystem or in the modules database. That means the uris and transform queries need to be able to be passed in as strings.

**Comment by mpheckel** [comment]
Agreed, ModuleExecutor will not solve that issue.  My suggestion was to address another issue you mentioned which was having to set up a two stage job when you only needed one.

**Comment by bbandlamudi** [comment]
I think, we can overload the existing URIS-MODULE, PROCESS-MODULE etc. If the value starts with a specific string such as "INLINE-XQUERY|" or "INLINE-JAVASCRIPT|", then what ever follows after can be read in as an adhoc query. This way, we can keep the code generic to all of the modules.
