### ISSUE TITLE
Remove compile warnings

### ISSUE THREAD

**Issue by rjrudin** [marklogic/corb2#11]
When I imported corb2 into eclipse (Luna), I get 132 compiler warnings. Most are easy fixes - unused imports, unused variables. But there are also a number of resource leaks, though most are in the test cases. 

I've pasted them below. I can put together a PR for this if others feel these are worth removing. 

Description	Resource	Path	Location	Type
BlockingQueue is a raw type. References to generic type BlockingQueue<E> should be parameterized	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 484	Java Problem
BlockingQueue is a raw type. References to generic type BlockingQueue<E> should be parameterized	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 507	Java Problem
Comparator is a raw type. References to generic type Comparator<T> should be parameterized	PostBatchUpdateFileTask.java	/corb2/src/main/java/com/marklogic/developer/corb	line 78	Java Problem
Comparator is a raw type. References to generic type Comparator<T> should be parameterized	PostBatchUpdateFileTask.java	/corb2/src/main/java/com/marklogic/developer/corb	line 105	Java Problem
List is a raw type. References to generic type List<E> should be parameterized	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 99	Java Problem
List is a raw type. References to generic type List<E> should be parameterized	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 107	Java Problem
Map.Entry is a raw type. References to generic type Map<K,V>.Entry<K,V> should be parameterized	Manager.java	/corb2/src/main/java/com/marklogic/developer/corb	line 292	Java Problem
Resource leak: '<unassigned Closeable value>' is never closed	TestUtils.java	/corb2/src/test/java/com/marklogic/developer/corb	line 79	Java Problem
Resource leak: 'br' is not closed at this location	HostKeyDecrypter.java	/corb2/src/main/java/com/marklogic/developer/corb	line 113	Java Problem
Resource leak: 'br' is not closed at this location	HostKeyDecrypter.java	/corb2/src/main/java/com/marklogic/developer/corb	line 113	Java Problem
Resource leak: 'br' is not closed at this location	HostKeyDecrypter.java	/corb2/src/main/java/com/marklogic/developer/corb	line 142	Java Problem
Resource leak: 'br' is not closed at this location	HostKeyDecrypter.java	/corb2/src/main/java/com/marklogic/developer/corb	line 142	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 69	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 78	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 90	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 102	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 111	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 123	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 132	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 177	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 191	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 201	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 208	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 222	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 229	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 248	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 264	Java Problem
Resource leak: 'instance' is never closed	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 299	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 73	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 85	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 99	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 130	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 144	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 185	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 198	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 212	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 230	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 251	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 262	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 273	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 283	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 294	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 310	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 344	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 367	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 376	Java Problem
Resource leak: 'instance' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 387	Java Problem
Resource leak: 'sc' is never closed	HostKeyDecrypter.java	/corb2/src/main/java/com/marklogic/developer/corb	line 76	Java Problem
Resource leak: 'writer' is never closed	QueryUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 179	Java Problem
The import java.io.BufferedReader is never used	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 21	Java Problem
The import java.io.File is never used	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 22	Java Problem
The import java.io.FileReader is never used	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 23	Java Problem
The import java.security.NoSuchAlgorithmException is never used	PostBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 34	Java Problem
The import java.util.Collection is never used	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 27	Java Problem
The import java.util.LinkedHashSet is never used	PostBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 37	Java Problem
The import java.util.logging.Level is never used	ModuleExecutorTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 47	Java Problem
The import java.util.logging.LogRecord is never used	ModuleExecutorTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 48	Java Problem
The import java.util.Set is never used	PostBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 39	Java Problem
The import javax.net.ssl.X509TrustManager is never used	TrustAnyoneSSLConfigTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 22	Java Problem
The import org.mockito.exceptions.base.MockitoException is never used	FileUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 35	Java Problem
The import org.mockito.Mockito.anyString is never used	ExportBatchToFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 29	Java Problem
The import org.mockito.Mockito.anyString is never used	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 33	Java Problem
The import org.mockito.Mockito.anyString is never used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 36	Java Problem
The import org.mockito.Mockito.anyString is never used	ModuleExecutorTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 51	Java Problem
The import org.mockito.Mockito.mock is never used	AbstractTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 57	Java Problem
The import org.mockito.Mockito.mock is never used	IOUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 39	Java Problem
The import org.mockito.Mockito.mock is never used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 37	Java Problem
The import org.mockito.Mockito.when is never used	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 35	Java Problem
The import org.mockito.Mockito.when is never used	IOUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 40	Java Problem
The import org.mockito.Mockito.when is never used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 38	Java Problem
The method decrypt(String) from the type JasyptDecrypterTest.TestDecrypt is never used locally	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 198	Java Problem
The method toURL() from the type File is deprecated	ModuleExecutorTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 531	Java Problem
The static field AbstractTask.MODULE_PROPS should be accessed in a static way	AbstractTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 268	Java Problem
The static field AbstractTask.MODULE_PROPS should be accessed in a static way	AbstractTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 269	Java Problem
The value of the local variable connectionUri is not used	ModuleExecutorTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 85	Java Problem
The value of the local variable context is not used	TwoWaySSLConfigTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 172	Java Problem
The value of the local variable expResult is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 424	Java Problem
The value of the local variable expResult is not used	TransformTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 73	Java Problem
The value of the local variable instance is not used	PostBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 411	Java Problem
The value of the local variable props is not used	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 1075	Java Problem
The value of the local variable records is not used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 91	Java Problem
The value of the local variable records is not used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 106	Java Problem
The value of the local variable records is not used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 125	Java Problem
The value of the local variable records is not used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 142	Java Problem
The value of the local variable records is not used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 154	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 111	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 153	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 172	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 181	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 187	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 193	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 199	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 219	Java Problem
The value of the local variable result is not used	AbstractManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 425	Java Problem
The value of the local variable result is not used	AbstractTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 267	Java Problem
The value of the local variable result is not used	ExportBatchToFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 90	Java Problem
The value of the local variable result is not used	ExportBatchToFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 100	Java Problem
The value of the local variable result is not used	ExportToFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 185	Java Problem
The value of the local variable result is not used	FileUrisLoaderTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 223	Java Problem
The value of the local variable result is not used	IOUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 137	Java Problem
The value of the local variable result is not used	IOUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 144	Java Problem
The value of the local variable result is not used	JasyptDecrypterTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 179	Java Problem
The value of the local variable result is not used	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 1037	Java Problem
The value of the local variable result is not used	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 1060	Java Problem
The value of the local variable result is not used	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 1068	Java Problem
The value of the local variable result is not used	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 1078	Java Problem
The value of the local variable result is not used	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 1105	Java Problem
The value of the local variable result is not used	PostBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 387	Java Problem
The value of the local variable result is not used	PostBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 402	Java Problem
The value of the local variable result is not used	PostBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 437	Java Problem
The value of the local variable result is not used	PostBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 448	Java Problem
The value of the local variable result is not used	PreBatchUpdateFileTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 123	Java Problem
The value of the local variable result is not used	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 159	Java Problem
The value of the local variable result is not used	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 260	Java Problem
The value of the local variable result is not used	StringUtilsTest.java	/corb2/src/test/java/com/marklogic/developer/corb/util	line 266	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 63	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 72	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 82	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 93	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 106	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 118	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 234	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 255	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 308	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 317	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 327	Java Problem
The value of the local variable result is not used	TaskFactoryTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 336	Java Problem
The value of the local variable value is not used	AbstractTaskTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 627	Java Problem
Type safety: The expression of type BlockingQueue needs unchecked conversion to conform to BlockingQueue<Runnable>	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 485	Java Problem
Type safety: The expression of type BlockingQueue needs unchecked conversion to conform to BlockingQueue<Runnable>	ManagerTest.java	/corb2/src/test/java/com/marklogic/developer/corb	line 508	Java Problem
Type safety: The expression of type Comparator needs unchecked conversion to conform to Comparator<String>	PostBatchUpdateFileTask.java	/corb2/src/main/java/com/marklogic/developer/corb	line 92	Java Problem
Type safety: The expression of type Comparator needs unchecked conversion to conform to Comparator<String>	PostBatchUpdateFileTask.java	/corb2/src/main/java/com/marklogic/developer/corb	line 97	Java Problem

**Comment by bbandlamudi** [comment]
Mads,
Could you please look into other warnings when you get a chance. I am not sure if these changes require a new release. The scanner resource leak (in master branch) for windows in HostKeyDecrypter has a minimal effect as we are closing the underlying the buffer reader anyway. Also, HostKeyDecrypter is called only once at the start (if used)

I made couple of changes (below) - 
1) Changed the function PostBatchUpdateFileTask.getComparatorCls function to return Comparator<String> and suppressing warnings for typecast as I couldn't find a better way to do it. 
2) In HostKeyDecrypter, scanner doesn't implement closeable in java 1.6. So, I changed the code to call close instead of FileUtils function.
