### ISSUE TITLE
MODULES-DATABASE parameter not used?

### ISSUE THREAD

**Issue by masyukun** [marklogic/corb2#17]
We have been observing the behavior that the MODULES-DATABASE properties parameter has no effect; it doesn't appear to override the associated modules database of the database specified in the connection string.

**Comment by bbandlamudi** [comment]
MODULES-DATABASE will only be used when you are trying to "install" modules from the file system into modules database. It is a legacy property and I haven't actually seen it being used anywhere and I wouldn't even bother specifying it. I didn't want to remove it for backwards compatibility.

**Comment by masyukun** [comment]
Thank you!

**Comment by grtjn** [comment]
Would have been useful for my case, see #143

**Comment by grtjn** [comment]
I'll leave it up to you guys to decide if this is worth reopening, or put some writing around it somewhere... you can work around with xdmp:invoke e.a., but that is a bit cumbersome..
