### ISSUE TITLE
Maven/Gradle: How can I get version 2.3.0?

### ISSUE THREAD

**Issue by sanderson-sfdc** [marklogic/corb2#20]
I'd like to try out version 2.3.0 as part of a gradle build, but it's not at http://developer.marklogic.com/maven2/ nor is it at JCenter.

**Comment by hansenmc** [comment]
Whoops! Apparently, getting listed in jcenter isn't automatic after publishing to bintray. I have submitted a request to have it published/hosted on the JCenter repository.

In the meantime, it is available at: https://dl.bintray.com/hansenmc/maven

You can add the following to your gradle.build repositories

```
    maven {
     url 'https://dl.bintray.com/hansenmc/maven'
    }
```

**Comment by hansenmc** [comment]
2.3.0 should now resolve from JCenter
