### ISSUE TITLE
Add CORB2 to MarkLogic develper maven repo

### ISSUE THREAD

**Issue by rjkennedy98** [marklogic/corb2#23]
The marklogic developer maven repository does not have CORB2. The repo is located here:
http://developer.marklogic.com/maven2/

**Comment by grechaw** [comment]
Hi @rjkennedy98 , just my own opinion, but for internal projects we've been preferring just to publish to maven central.  The internal repo is manually maintained and it's kind of a pain.

@kkanthet  is familiar with the process of getting jars on maven central -- you may want to ask him about that.

**Comment by rjkennedy98** [comment]
@grechaw yeah as long as I can use an existing maven repo and don't have to refer to a local repo, I am good.

**Comment by hansenmc** [comment]
We just started publishing CORB to bintray. https://bintray.com/marklogic/maven/marklogic-corb/view

It is available via jcenter() now. I'm working to get permission to sync/publish to maven central as well.

**Comment by hansenmc** [comment]
@rjkennedy98 There are a few additional things that we need to take care of (enhance the published pom.xml, generate and publish javadocs), before we can get the corb jars published in Maven Central. 

Meantime, you can also resolve the latest corb jar from the bintray maven repo:
```
<repositories>
  <repository>
    <id>bintray-marklogic-maven</id>
    <name>bintray</name>
    <url>http://dl.bintray.com/marklogic/maven</url>
  </repository>
</repositories>
```

**Comment by hansenmc** [comment]
v2.3.1 is now available in Maven Central! 
https://repo1.maven.org/maven2/com/marklogic/marklogic-corb/2.3.1/
