### ISSUE TITLE
Support automatic retries for uris, pre and post batch module executions. 

### ISSUE THREAD

**Issue by bbandlamudi** [marklogic/corb2#27]
Corb automatically retries only transform failures. We should extend this functionality to uris, pre and post batch module executions as well.

**Comment by hansenmc** [comment]
We should only have to adjust the QueryUrisLoader for retries. 

Both PreBatchUpdateFileTask and PostBatchUpdateFileTask inherit the retry behavior defined in AbstractTask, through extension of ExportBatchToFileTask --> ExportToFileTask --> AbstractTask. I added two unit tests in the Pre/PostBatchUpdateFileTaskTest to verify/demonstrate retry.

**Comment by bbandlamudi** [comment]
Thanks Mads! You are right, I forgot that these tasks inherit the retry behavior from AbstractTask. It is not so important for uris loader to be able retry, if it fails, we can simply restart the entire job with a problem.. I was mostly worried about the post batch task. We can close the issue.
