### ISSUE TITLE
Custom Variables From Selector Not Being Passed

### ISSUE THREAD

**Issue by mpheckel** [marklogic/corb2#29]
I was trying to pass dynamically created custom vars from the selector but received an error on the transform side.  I was able to get them working but only after I had changed the name of the variables.  Originally, the variables had hyphens in them as in URIS-MODULE.my-custom-var="blah".  It was only after removing the hyphens that it worked: URIS-MODULE.myCustomVar="blah".  I'm not sure if underscores work either..

Request that either they be allowed to be used or the readME be updated to alert users of the limitation.  They are very handy, thanks!

**Comment by hansenmc** [comment]
@mpheckel The regex pattern is currently only matching alpha numeric values for the property name. https://github.com/marklogic/corb2/blob/master/src/main/java/com/marklogic/developer/corb/QueryUrisLoader.java#L56

We should support dash `-` and underscore `_`.

**Comment by hansenmc** [comment]
@mpheckel I have adjusted the regex pattern to include "-" and "_" and pushed to the development branch. It will be included in the next release.
