### ISSUE TITLE
Support JavaScript modules

### ISSUE THREAD

**Issue by dmcassel** [marklogic/corb2#3]
Add support for calling JavaScript modules. 

FYI, I ran a test with Corb 1 and found I could use a JavaScript transformation module, but not for getting URIs. For the transformation module, "URI" just works as a global (rather than external) variable.

**Comment by bbandlamudi** [comment]
Thanks for the ticket! Support for javascript modules (including adhoc queries) has been added to https://github.com/marklogic/corb2/tree/corb2-dev. I will work on the documentation to reflect the new changes.

**Comment by dmcassel** [comment]
Awesome, thanks for implementing it.

**Comment by bbandlamudi** [comment]
Changes have been merged into master along with updates to documentation. The latest corb v2.1.2 supports java script modules which can be downloaded from releases.
