### ISSUE TITLE
The latest corb removed WARNING: Slow receive! Consider increasing max heap...

### ISSUE THREAD

**Issue by bbandlamudi** [marklogic/corb2#33]
A user has reported an issue about this warning and I noticed that we are no longer printing this. This use case happens with two use cases - 1) memory is two low 2) fetch rate from ML is slow. The case I have seen today appears to be related to fetch rate as memory is fine. We should continue to print this warning and improve the error message based on which case it is. 

Also, the QueryUrisLoader logQueueStatus may need to check the memory a bit more frequently - need to check performance implications here.

**Comment by hansenmc** [comment]
I had dropped it in the refactor and integration of the disk backed queue, and was thinking it would be less needed if we were spilling large URIs lists to disk. I have put it back in as it was and will look at maybe adjusting the message based upon time vs memory. 

If less than X% available, change memory log message from info to warn?

**Comment by bbandlamudi** [comment]
I think, that would help.. it is a good idea periodically check the heap and if the memory is too low, we should print a warning.
