### ISSUE TITLE
PROCESS-MODULE ignored

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/corb2#48]
my options file:

MODULE-ROOT=/corb/
PROCESS-MODULE=getContractorUris.sjs
THREAD-COUNT=4
URIS-MODULE=addProp.sjs
XCC-USERNAME=admin
XCC-PASSWORD=admin
XCC-HOSTNAME=ea4-ml1
XCC-PORT=8030

my corb invoke (using latest roxy):

```
./ml local corb -DOPTIONS-FILE=./corb-config/test.properties
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/smitrovi/apps/mlcp-8.0-5/bin in PATH, mode 040777
logging to CONSOLE
Mar 13, 2017 10:53:36 AM com.marklogic.developer.SimpleLogger configureLogger
INFO: setting up logging for: com.marklogic.ps
Mar 13, 2017 10:53:36 AM com.marklogic.developer.corb.Manager loadPropertiesFile
INFO: Loading ./corb-config/test.properties from filesystem
Exception in thread "main" java.lang.NullPointerException: PROCESS-TASK or XQUERY-MODULE must be specified
	at com.marklogic.developer.corb.Manager.createManager(Manager.java:371)
	at com.marklogic.developer.corb.Manager.main(Manager.java:182)
```

If I change PROCESS-MODULE to XQUERY-MODULE than the error doesn't pop-up anymore.

**Comment by bbandlamudi** [comment]
Which version of Corb are you using? In the later versions of Corb, the exception would actually say - "PROCESS-TASK or PROCESS-MODULE must be specified". Please try using the latest version of Corb.. if still an issue, it may be because value isn't getting passed through roxy

**Comment by hansenmc** [comment]
@sashamitrovich Double check to see if there might be multiple CoRB jar files in your Roxy deploy/lib/java/ directory. The only CoRB jar that you want is `/deploy/lib/java/marklogic-corb-2.3.2.jar`.

The [find_jar()](https://github.com/marklogic/roxy/blob/36cbdb7757dab0834db6831d73792de9440aa3b6/deploy/lib/util.rb#L222) method used to load jar files uses a glob pattern. It could be that you are loading an older CoRB jar by accident. If you are using the latest Roxy, it should have `/deploy/lib/java/marklogic-corb-2.3.2.jar`, but previously had the ambiguous, non-versioned jar filename `corb.jar` which might get picked up first. 

If your Roxy install has /deploy/lib/java/corb.jar, remove it (and the marklogic-corb-2.3.1.jar if it is there as well), and re-try.

**Comment by sashamitrovich** [comment]
My Roxy only has `/marklogic-corb-2.3.2.jar`

<img width="281" alt="screen shot 2017-03-16 at 15 17 23" src="https://cloud.githubusercontent.com/assets/15609655/24000649/205ed25a-0a5c-11e7-9311-ba91c2f58419.png">

**Comment by hansenmc** [comment]
Hmm, that is very confusing. That error message is produced from within the Manager class. 

In [version **2.3.2**](https://github.com/marklogic/corb2/blob/2.3.2/src/main/java/com/marklogic/developer/corb/Manager.java#L316): 

    if (null == options.getProcessTaskClass() && null == options.getProcessModule()) {
      throw new NullPointerException(PROCESS_TASK + " or " + PROCESS_MODULE + " must be specified");
    }

The last version that had that specific error message was in [version **2.1.3**](https://github.com/marklogic/corb2/blob/2.1.3/src/main/java/com/marklogic/developer/corb/Manager.java#L371):

    if(null == options.getProcessTaskClass() && null == options.getProcessModule()){
      throw new NullPointerException("PROCESS-TASK or XQUERY-MODULE must be specified");
    }

So, it seems that you are somehow loading an older version of CoRB2. 

However, I don't see how Roxy would load anything other than what is in the `./deploy/lib/java/` directory with the [find_jar()](https://github.com/marklogic/roxy/blob/master/deploy/lib/util.rb#L222) method inside of the [corb task](https://github.com/marklogic/roxy/blob/36cbdb7757dab0834db6831d73792de9440aa3b6/deploy/lib/server_config.rb#L1346):

    corb_file = find_jar('corb')
    xcc_file = find_jar('xcc')

    runme = %Q{java -cp #{corb_file}#{path_separator}#{xcc_file} #{systemProperties} com.marklogic.developer.corb.Manager #{connection_string}}
    logger.debug runme

Could you try deleting or renaming that CoRB2 jar from your `/deploy/lib/java/`, and see if the task fails when it can't find that jar file (or still executes and is running with a jar from another location)?

**Comment by hansenmc** [comment]
@sashamitrovich any updates on this?

I pulled the latest Roxy, initialized a test project, and invoked a corb job with your sample options. It worked (or at least made it past the step you were failing on before the job failed with an XDMP-MODNOTFOUND because I didn't load an addProps.sjs URIS module). 

When I comment out the **PROCESS-MODULE** property and re-run, then I get the expected error message:

 `./ml local corb -DOPTIONS-FILE=./corb-config/test.properties --ml.xcc-port=8223 --ml.content-db=marklogic-corb-content --ml.modules-db=marklogic-corb-modules`

> Mar 26, 2017 11:00:09 PM com.marklogic.developer.corb.AbstractManager loadPropertiesFile
> INFO: Loading ./corb-config/test.properties from filesystem
> Mar 26, 2017 11:00:09 PM com.marklogic.developer.corb.Manager main
> SEVERE: Error initializing CORB PROCESS-TASK or PROCESS-MODULE must be specified

**Comment by hansenmc** [comment]
Confirmed that an older version of CoRB was being executed, due to issues upgrading Roxy.
