### ISSUE TITLE
ValueIterator doesn't have count property

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/corb2#49]
JavaScript example (https://github.com/marklogic/corb2#javascript-modules):

```
var uris = cts.uris()
fn.insertBefore(uris,0,uris.count)
```

will not work because uris.count return null.

Suggested fix:

```
var uris = cts.uris()
fn.insertBefore(uris,0,fn.count(uris))
```

**Comment by bbandlamudi** [comment]
I just tested the above by inserting two documents into Documents db and the above script worked fine i.e., both uris.count and fn.count(uris) worked. Could you please check! If an issue, we can change the document or even if not an issue, we can still list fn.count(uris) as an alternative.

**Comment by hansenmc** [comment]
@sashamitrovich Are you using an EA version of MarkLogic 9? 

I see that the [ValueIterator.count](https://docs.marklogic.com/ValueIterator.count) is deprecated. When I run under ML 8.0-5.8, it works as expected, but in ML 9 EA4, `uris.count` is null.

So, looks as if we should update the documentation to use `fn.count()` instead.

**Comment by sashamitrovich** [comment]
Sorry for the confusion, didn't specify I'm using ML9. I'd go for fn.count(), yes. Thanks!
