### ISSUE TITLE
Sample Processing Module wiki only shows reporting

### ISSUE THREAD

**Issue by dmcassel** [marklogic/corb2#8]
The wiki page with the Sample Processing Module only shows a reporting example; there isn't one for actually reprocessing (modifying documents), which is CORB's core use case. Add a wiki that gives a reprocessing example. 

There is a wiki for Updating a Node in a Document, but it doesn't include the code.

**Comment by mpheckel** [comment]
Added another example to the Sample Processing Module which adds a node to a document.  Also added a link to the code from the Wiki page "Example: Updating a Node in a Document"

**Comment by dmcassel** [comment]
thanks @mpheckel
